# Generated by Django 2.2.5 on 2019-10-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Teach_Nonteach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(choices=[('HOD & Prof', 'HOD & Prof'), ('Prof', 'Prof'), ('Asc Prof', 'Asc Prof'), ('Asst Prof', 'Asst Prof'), ('Attender', 'Attender'), ('Foreman', 'Foreman'), ('Watchman', 'Watchman'), ('Lab Tech', 'Lab Tech'), ('Instructor', 'Instructor')], default='Asst Prof', max_length=20)),
                ('Type', models.CharField(choices=[('Teaching', 'Teaching'), ('Non_Teaching', 'Non-Teaching')], default='Teaching', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('F_Name', models.CharField(max_length=40)),
                ('F_Type', models.CharField(choices=[('Teaching', 'Teaching'), ('Non_Teaching', 'Non-Teaching')], default='Teaching', max_length=20)),
                ('Dept', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('EC', 'EC'), ('CV', 'CV'), ('ME', 'ME'), ('ME', 'ME'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('AFMA', 'AFMA'), ('Office', 'Office'), ('Security', 'Security')], default='CS', max_length=10)),
                ('Qualification', models.CharField(max_length=50)),
                ('Experience', models.IntegerField()),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Date_Of_Join', models.DateField()),
                ('Working_Status', models.BooleanField(default=True)),
                ('F_Designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.F_Teach_Nonteach')),
            ],
        ),
    ]
