# Generated by Django 2.2.5 on 2019-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_f_teach_nonteach_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_teach_nonteach',
            name='Designation',
            field=models.CharField(choices=[('HOD & Prof', 'HOD & Prof'), ('Prof', 'Prof'), ('Asc Prof', 'Asc Prof'), ('Asst Prof', 'Asst Prof'), ('Attender', 'Attender'), ('Foreman', 'Foreman'), ('Watchman', 'Watchman'), ('Lab Tech', 'Lab Tech'), ('Instructor', 'Instructor')], default='Asst Prof', max_length=20, unique=True),
        ),
    ]
