# Generated by Django 2.2.5 on 2019-10-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20191026_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee_str',
            name='Spor_13',
        ),
        migrations.RemoveField(
            model_name='fee_str',
            name='Tran_14',
        ),
        migrations.AddField(
            model_name='fee_str',
            name='Spor_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fee_str',
            name='Tran_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fee_str',
            name='Tuti_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Apti_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Book_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Conf_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='IndP_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='IndV_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Inte_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Libr_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Semi_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Soft_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Subj_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Tech_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee_str',
            name='Volu_15',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Stud_Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apti_1_Paid', models.BooleanField(default=False)),
                ('Tech_2_Paid', models.BooleanField(default=False)),
                ('Book_3_Paid', models.BooleanField(default=False)),
                ('IndP_4_Paid', models.BooleanField(default=False)),
                ('IndV_5_Paid', models.BooleanField(default=False)),
                ('Inte_6_Paid', models.BooleanField(default=False)),
                ('Libr_7_Paid', models.BooleanField(default=False)),
                ('Semi_8_Paid', models.BooleanField(default=False)),
                ('Soft_9_Paid', models.BooleanField(default=False)),
                ('Conf_10_Paid', models.BooleanField(default=False)),
                ('Subj_11_Paid', models.BooleanField(default=False)),
                ('Spor_12_Paid', models.BooleanField(default=False)),
                ('Tran_13_Paid', models.BooleanField(default=False)),
                ('Tuti_14_Paid', models.BooleanField(default=False)),
                ('Volu_15_Paid', models.BooleanField(default=False)),
                ('Total', models.IntegerField()),
                ('Paid', models.IntegerField()),
                ('Due', models.IntegerField()),
                ('Date_Paid', models.DateTimeField(auto_now=True)),
                ('Adm_No_S', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.Stud_Admn')),
            ],
        ),
    ]
