# Generated by Django 2.2.5 on 2019-11-02 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0005_auto_20191101_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_pd',
            old_name='added_by',
            new_name='Added_by',
        ),
        migrations.AddField(
            model_name='faculty',
            name='Username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
