# Generated by Django 2.2.5 on 2019-11-02 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_auto_20191101_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
