# Generated by Django 2.2.5 on 2019-11-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20191101_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_fees',
            old_name='Date_Paid',
            new_name='Last_Date_Paid',
        ),
        migrations.AlterField(
            model_name='stud_admn',
            name='Fid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='entry.Fee_Str'),
        ),
        migrations.AlterField(
            model_name='stud_fees',
            name='Adm_No_S',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='entry.Stud_Admn'),
        ),
        migrations.CreateModel(
            name='Fee_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee_Paid', models.IntegerField(default=0)),
                ('Date_Paid', models.DateTimeField(auto_now_add=True)),
                ('Stud_Fee_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.Stud_Fees')),
            ],
        ),
    ]
