# Generated by Django 2.2.5 on 2019-11-02 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20191101_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Username',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
