# Generated by Django 2.2.5 on 2019-11-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20191102_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_admn',
            name='Adm_Year',
            field=models.IntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020')], default=2019),
        ),
    ]
