# Generated by Django 2.2.5 on 2019-11-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0011_stud_admn_adm_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_record',
            name='Added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
