# Generated by Django 2.2.5 on 2019-11-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_fee_record_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_fees',
            name='Paid',
            field=models.IntegerField(default=0),
        ),
    ]
