# Generated by Django 2.2.5 on 2019-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20191102_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_record',
            name='truedd',
            field=models.BooleanField(default=True),
        ),
    ]
