# Generated by Django 2.2.5 on 2019-11-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_fee_record_truedd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee_record',
            name='truedd',
        ),
    ]
